#开发环境
web:
    upload-path: F:/upload/
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/shangpin_video?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true&useSSL=true
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 5
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
  redis:
      database: 1
      host: 192.168.2.66
      port: 6379
      password: 123123
      timeout: 0
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 0
logging:
  config: classpath:logback-dev.xml